name: Chế độ an toàn nội dung tự động
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"  # Chạy tự động mỗi 12 giờ (UTC)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Safe Mode job
        env:
          WORDPRESS_BASE_URL: ${{ secrets.WORDPRESS_BASE_URL }}
          WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
          WORDPRESS_APP_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SAFE_MODE: "true"          # Luôn kích hoạt chế độ an toàn
          TZ: Asia/Ho_Chi_Minh       # Múi giờ Việt Nam cho log
        run: |
          # Thực thi một vòng thu thập và đăng nội dung ở chế độ an toàn
          python app/main.py --once || python app/main.py
