name: Run main.py on schedule

# Kích hoạt workflow khi push code lên nhánh chính hoặc theo lịch đặt trước
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 6 * * *"   # Ví dụ: chạy mỗi ngày lúc 6:00 UTC
  workflow_dispatch:      # Cho phép chạy thủ công

jobs:
  run-script:
    runs-on: ubuntu-latest

    # Thiết lập các biến môi trường từ Secrets
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      WORDPRESS_BASE_URL: ${{ secrets.WORDPRESS_BASE_URL }}
      WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
      WORDPRESS_APP_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}
      SAFE_MODE: ${{ secrets.SAFE_MODE }}
      TZ: ${{ secrets.TZ }}

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Fallback: đảm bảo cài thư viện schedule nếu chưa có
          pip install schedule

      - name: Run main script
        run: python main.py --once
